version: "3"
services:
  nginx:
    image: nginx
    ports:
      # ホスト:コンテナ
      - "8000:81"
    depends_on:
      - app
      # - front
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www

  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www/api
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
